### ISSUE TITLE
normalize does not work correctly

### ISSUE THREAD

**Issue by SergeStinckwich** [KendrickOrg/kendrick#393]
```Smalltalk
expr := 'X:t = -(-A*(B+C))' parseAsAnEquation.
expr expression normalize.
```
returns the correct expression

```Smalltalk
expr := 'X:t=-(-A)' parseAsAnEquation.
expr expression normalize.
```

returns the correct expression

```Smalltalk
expr := 'X:t=A+(-B)' parseAsAnEquation.
expr expression normalize.
```
returns -(A+B)

**Comment by YvanGuifo** [comment]
I modified the `normalize` method the class `KEBinaryExpression`

**Comment by SergeStinckwich** [comment]
To do what? Can can you be more explicit?

**Comment by YvanGuifo** [comment]
In order to have the right return values when evaluating the expressions

**Comment by SergeStinckwich** [comment]
You have to add a test for this issue and try to made it pass.

**Comment by YvanGuifo** [comment]
I added a test
